import kainat_linkedlist
from kainat_linkedlist import *

L1=linked_list()
# L1.add_in_list_first(10)
# L1.add_in_list_first(20)
# L1.add_in_list_first(30)
# L1.add_in_list_first(40)
# L1.add_in_list_first(50)
# L1.add_in_list_last(60)
L1.add_between(15, 20)
L1.add_between(16, 15)
L1.add_between(17, 15)
L1.show_in_list()
# print('\n')
# L1.del_from_list_last()
# L1.show_in_list()
# print('\n')
# L1.del_from_list_first()
# L1.show_in_list()
